// Mocks generated by Mockito 5.4.6 from annotations
// in my_first_app/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i10;
import 'dart:typed_data' as _i12;

import 'package:dio/src/adapter.dart' as _i2;
import 'package:dio/src/options.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:my_first_app/app/config/app_config.dart' as _i31;
import 'package:my_first_app/features/auth/data/auth_service.dart' as _i15;
import 'package:my_first_app/features/auth/data/models/user_info.dart' as _i3;
import 'package:my_first_app/features/auth/data/token_store.dart' as _i13;
import 'package:my_first_app/features/cart/data/cart_service.dart' as _i16;
import 'package:my_first_app/features/cart/data/models/cart_vo.dart' as _i4;
import 'package:my_first_app/features/order/data/models/order_vo.dart' as _i20;
import 'package:my_first_app/features/order/data/order_service.dart' as _i19;
import 'package:my_first_app/features/payment/application/payment_gateway.dart'
    as _i24;
import 'package:my_first_app/features/payment/application/payment_order_provider.dart'
    as _i29;
import 'package:my_first_app/features/payment/application/payment_sdk_initializer.dart'
    as _i30;
import 'package:my_first_app/features/payment/application/payment_service.dart'
    as _i22;
import 'package:my_first_app/features/payment/data/models/alipay_payment_payload.dart'
    as _i9;
import 'package:my_first_app/features/payment/data/models/pay_result_vo.dart'
    as _i5;
import 'package:my_first_app/features/payment/data/models/payment_request.dart'
    as _i25;
import 'package:my_first_app/features/payment/data/pay_service.dart' as _i21;
import 'package:my_first_app/features/payment/presentation/models/payment_method.dart'
    as _i23;
import 'package:my_first_app/features/payment/presentation/models/payment_result.dart'
    as _i6;
import 'package:my_first_app/features/product/data/models/category_node.dart'
    as _i28;
import 'package:my_first_app/features/product/data/models/page_result.dart'
    as _i7;
import 'package:my_first_app/features/product/data/models/product_detail.dart'
    as _i8;
import 'package:my_first_app/features/product/data/models/product_summary.dart'
    as _i27;
import 'package:my_first_app/features/product/data/product_service.dart'
    as _i26;
import 'package:my_first_app/features/profile/data/address_service.dart'
    as _i17;
import 'package:my_first_app/features/profile/data/models/address_vo.dart'
    as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponseBody_0 extends _i1.SmartFake implements _i2.ResponseBody {
  _FakeResponseBody_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResult_1 extends _i1.SmartFake implements _i3.LoginResult {
  _FakeLoginResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserInfo_2 extends _i1.SmartFake implements _i3.UserInfo {
  _FakeUserInfo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartVO_3 extends _i1.SmartFake implements _i4.CartVO {
  _FakeCartVO_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayResultVO_4 extends _i1.SmartFake implements _i5.PayResultVO {
  _FakePayResultVO_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentResult_5 extends _i1.SmartFake implements _i6.PaymentResult {
  _FakePaymentResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePageResult_6<T> extends _i1.SmartFake implements _i7.PageResult<T> {
  _FakePageResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductDetail_7 extends _i1.SmartFake implements _i8.ProductDetail {
  _FakeProductDetail_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlipayPaymentPayload_8 extends _i1.SmartFake
    implements _i9.AlipayPaymentPayload {
  _FakeAlipayPaymentPayload_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClientAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientAdapter extends _i1.Mock implements _i2.HttpClientAdapter {
  @override
  _i10.Future<_i2.ResponseBody> fetch(
    _i11.RequestOptions? options,
    _i10.Stream<_i12.Uint8List>? requestStream,
    _i10.Future<void>? cancelFuture,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [options, requestStream, cancelFuture]),
            returnValue: _i10.Future<_i2.ResponseBody>.value(
              _FakeResponseBody_0(
                this,
                Invocation.method(#fetch, [
                  options,
                  requestStream,
                  cancelFuture,
                ]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i2.ResponseBody>.value(
              _FakeResponseBody_0(
                this,
                Invocation.method(#fetch, [
                  options,
                  requestStream,
                  cancelFuture,
                ]),
              ),
            ),
          )
          as _i10.Future<_i2.ResponseBody>);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TokenStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStore extends _i1.Mock implements _i13.TokenStore {
  @override
  _i10.Future<String?> readToken() =>
      (super.noSuchMethod(
            Invocation.method(#readToken, []),
            returnValue: _i10.Future<String?>.value(),
            returnValueForMissingStub: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> readOrCreateClientId() =>
      (super.noSuchMethod(
            Invocation.method(#readOrCreateClientId, []),
            returnValue: _i10.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#readOrCreateClientId, []),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#readOrCreateClientId, []),
              ),
            ),
          )
          as _i10.Future<String>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i15.AuthService {
  @override
  _i10.Future<_i3.LoginResult> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i10.Future<_i3.LoginResult>.value(
              _FakeLoginResult_1(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i3.LoginResult>.value(
              _FakeLoginResult_1(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.LoginResult>);

  @override
  _i10.Future<void> register({
    required String? username,
    required String? password,
    String? nickname,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #username: username,
              #password: password,
              #nickname: nickname,
              #phone: phone,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i3.UserInfo> fetchCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentUser, []),
            returnValue: _i10.Future<_i3.UserInfo>.value(
              _FakeUserInfo_2(this, Invocation.method(#fetchCurrentUser, [])),
            ),
            returnValueForMissingStub: _i10.Future<_i3.UserInfo>.value(
              _FakeUserInfo_2(this, Invocation.method(#fetchCurrentUser, [])),
            ),
          )
          as _i10.Future<_i3.UserInfo>);
}

/// A class which mocks [CartService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartService extends _i1.Mock implements _i16.CartService {
  @override
  _i10.Future<_i4.CartVO> fetchCart() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCart, []),
            returnValue: _i10.Future<_i4.CartVO>.value(
              _FakeCartVO_3(this, Invocation.method(#fetchCart, [])),
            ),
            returnValueForMissingStub: _i10.Future<_i4.CartVO>.value(
              _FakeCartVO_3(this, Invocation.method(#fetchCart, [])),
            ),
          )
          as _i10.Future<_i4.CartVO>);

  @override
  _i10.Future<void> addItem({required int? skuId, int? quantity = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#addItem, [], {
              #skuId: skuId,
              #quantity: quantity,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updateQuantity({
    required int? itemId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [], {
              #itemId: itemId,
              #quantity: quantity,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> removeItem(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [itemId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setItemChecked({
    required int? itemId,
    required bool? checked,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setItemChecked, [], {
              #itemId: itemId,
              #checked: checked,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setAllChecked({required bool? checked}) =>
      (super.noSuchMethod(
            Invocation.method(#setAllChecked, [], {#checked: checked}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> removeCheckedItems() =>
      (super.noSuchMethod(
            Invocation.method(#removeCheckedItems, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [AddressService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressService extends _i1.Mock implements _i17.AddressService {
  @override
  _i10.Future<List<_i18.AddressVO>> fetchAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAddresses, []),
            returnValue: _i10.Future<List<_i18.AddressVO>>.value(
              <_i18.AddressVO>[],
            ),
            returnValueForMissingStub: _i10.Future<List<_i18.AddressVO>>.value(
              <_i18.AddressVO>[],
            ),
          )
          as _i10.Future<List<_i18.AddressVO>>);

  @override
  _i10.Future<int> addAddress({
    required String? receiverName,
    required String? receiverPhone,
    required String? province,
    required String? city,
    required String? district,
    required String? detailAddress,
    bool? isDefault = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAddress, [], {
              #receiverName: receiverName,
              #receiverPhone: receiverPhone,
              #province: province,
              #city: city,
              #district: district,
              #detailAddress: detailAddress,
              #isDefault: isDefault,
            }),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<void> updateAddress({
    required int? id,
    required String? receiverName,
    required String? receiverPhone,
    required String? province,
    required String? city,
    required String? district,
    required String? detailAddress,
    bool? isDefault = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddress, [], {
              #id: id,
              #receiverName: receiverName,
              #receiverPhone: receiverPhone,
              #province: province,
              #city: city,
              #district: district,
              #detailAddress: detailAddress,
              #isDefault: isDefault,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAddress(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setDefaultAddress(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultAddress, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [OrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderService extends _i1.Mock implements _i19.OrderService {
  @override
  _i10.Future<List<_i20.OrderVO>> fetchOrders({int? current = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrders, [], {#current: current}),
            returnValue: _i10.Future<List<_i20.OrderVO>>.value(
              <_i20.OrderVO>[],
            ),
            returnValueForMissingStub: _i10.Future<List<_i20.OrderVO>>.value(
              <_i20.OrderVO>[],
            ),
          )
          as _i10.Future<List<_i20.OrderVO>>);

  @override
  _i10.Future<String> createOrder({required int? addressId, String? remark}) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [], {
              #addressId: addressId,
              #remark: remark,
            }),
            returnValue: _i10.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#createOrder, [], {
                  #addressId: addressId,
                  #remark: remark,
                }),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#createOrder, [], {
                  #addressId: addressId,
                  #remark: remark,
                }),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> confirmReceipt(String? orderNo) =>
      (super.noSuchMethod(
            Invocation.method(#confirmReceipt, [orderNo]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> cancelOrder(String? orderNo) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOrder, [orderNo]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [PayService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayService extends _i1.Mock implements _i21.PayService {
  @override
  _i10.Future<_i5.PayResultVO> mockPay(String? orderNo) =>
      (super.noSuchMethod(
            Invocation.method(#mockPay, [orderNo]),
            returnValue: _i10.Future<_i5.PayResultVO>.value(
              _FakePayResultVO_4(this, Invocation.method(#mockPay, [orderNo])),
            ),
            returnValueForMissingStub: _i10.Future<_i5.PayResultVO>.value(
              _FakePayResultVO_4(this, Invocation.method(#mockPay, [orderNo])),
            ),
          )
          as _i10.Future<_i5.PayResultVO>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i22.PaymentService {
  @override
  Map<_i23.PaymentMethod, _i24.PaymentGateway> get gateways =>
      (super.noSuchMethod(
            Invocation.getter(#gateways),
            returnValue: <_i23.PaymentMethod, _i24.PaymentGateway>{},
            returnValueForMissingStub:
                <_i23.PaymentMethod, _i24.PaymentGateway>{},
          )
          as Map<_i23.PaymentMethod, _i24.PaymentGateway>);

  @override
  _i10.Future<_i6.PaymentResult> pay(_i25.PaymentRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#pay, [request]),
            returnValue: _i10.Future<_i6.PaymentResult>.value(
              _FakePaymentResult_5(this, Invocation.method(#pay, [request])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.PaymentResult>.value(
              _FakePaymentResult_5(this, Invocation.method(#pay, [request])),
            ),
          )
          as _i10.Future<_i6.PaymentResult>);
}

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i26.ProductService {
  @override
  _i10.Future<_i7.PageResult<_i27.ProductSummary>> fetchProducts({
    int? categoryId,
    String? keyword,
    int? current = 1,
    int? size = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {
              #categoryId: categoryId,
              #keyword: keyword,
              #current: current,
              #size: size,
            }),
            returnValue: _i10.Future<_i7.PageResult<_i27.ProductSummary>>.value(
              _FakePageResult_6<_i27.ProductSummary>(
                this,
                Invocation.method(#fetchProducts, [], {
                  #categoryId: categoryId,
                  #keyword: keyword,
                  #current: current,
                  #size: size,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i7.PageResult<_i27.ProductSummary>>.value(
                  _FakePageResult_6<_i27.ProductSummary>(
                    this,
                    Invocation.method(#fetchProducts, [], {
                      #categoryId: categoryId,
                      #keyword: keyword,
                      #current: current,
                      #size: size,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i7.PageResult<_i27.ProductSummary>>);

  @override
  _i10.Future<_i8.ProductDetail> fetchProductDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductDetail, [id]),
            returnValue: _i10.Future<_i8.ProductDetail>.value(
              _FakeProductDetail_7(
                this,
                Invocation.method(#fetchProductDetail, [id]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i8.ProductDetail>.value(
              _FakeProductDetail_7(
                this,
                Invocation.method(#fetchProductDetail, [id]),
              ),
            ),
          )
          as _i10.Future<_i8.ProductDetail>);

  @override
  _i10.Future<List<_i28.CategoryNode>> fetchCategoryTree() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategoryTree, []),
            returnValue: _i10.Future<List<_i28.CategoryNode>>.value(
              <_i28.CategoryNode>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i28.CategoryNode>>.value(
                  <_i28.CategoryNode>[],
                ),
          )
          as _i10.Future<List<_i28.CategoryNode>>);
}

/// A class which mocks [PaymentGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentGateway extends _i1.Mock implements _i24.PaymentGateway {
  @override
  _i10.Future<_i6.PaymentResult> pay(_i25.PaymentRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#pay, [request]),
            returnValue: _i10.Future<_i6.PaymentResult>.value(
              _FakePaymentResult_5(this, Invocation.method(#pay, [request])),
            ),
            returnValueForMissingStub: _i10.Future<_i6.PaymentResult>.value(
              _FakePaymentResult_5(this, Invocation.method(#pay, [request])),
            ),
          )
          as _i10.Future<_i6.PaymentResult>);
}

/// A class which mocks [PaymentOrderProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentOrderProvider extends _i1.Mock
    implements _i29.PaymentOrderProvider {
  @override
  _i10.Future<_i9.AlipayPaymentPayload> fetchAlipayPayload(
    _i25.PaymentRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAlipayPayload, [request]),
            returnValue: _i10.Future<_i9.AlipayPaymentPayload>.value(
              _FakeAlipayPaymentPayload_8(
                this,
                Invocation.method(#fetchAlipayPayload, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i10.Future<_i9.AlipayPaymentPayload>.value(
                  _FakeAlipayPaymentPayload_8(
                    this,
                    Invocation.method(#fetchAlipayPayload, [request]),
                  ),
                ),
          )
          as _i10.Future<_i9.AlipayPaymentPayload>);
}

/// A class which mocks [PaymentSdkInitializer].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentSdkInitializer extends _i1.Mock
    implements _i30.PaymentSdkInitializer {
  @override
  _i10.Future<void> initialize(_i31.AppConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [config]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}
