// Mocks generated by Mockito 5.4.6 from annotations
// in my_first_app/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i7;
import 'dart:typed_data' as _i9;

import 'package:dio/src/adapter.dart' as _i2;
import 'package:dio/src/options.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:my_first_app/app/config/app_config.dart' as _i18;
import 'package:my_first_app/features/auth/data/auth_service.dart' as _i12;
import 'package:my_first_app/features/auth/data/models/user_info.dart' as _i3;
import 'package:my_first_app/features/auth/data/token_store.dart' as _i10;
import 'package:my_first_app/features/home/data/home_recommend_service.dart'
    as _i13;
import 'package:my_first_app/features/home/presentation/models/home_recommend_product.dart'
    as _i4;
import 'package:my_first_app/features/payment/application/payment_gateway.dart'
    as _i14;
import 'package:my_first_app/features/payment/application/payment_order_provider.dart'
    as _i16;
import 'package:my_first_app/features/payment/application/payment_sdk_initializer.dart'
    as _i17;
import 'package:my_first_app/features/payment/data/models/alipay_payment_payload.dart'
    as _i6;
import 'package:my_first_app/features/payment/data/models/payment_request.dart'
    as _i15;
import 'package:my_first_app/features/payment/presentation/models/payment_result.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponseBody_0 extends _i1.SmartFake implements _i2.ResponseBody {
  _FakeResponseBody_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResult_1 extends _i1.SmartFake implements _i3.LoginResult {
  _FakeLoginResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserInfo_2 extends _i1.SmartFake implements _i3.UserInfo {
  _FakeUserInfo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeRecommendPageResult_3 extends _i1.SmartFake
    implements _i4.HomeRecommendPageResult {
  _FakeHomeRecommendPageResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentResult_4 extends _i1.SmartFake implements _i5.PaymentResult {
  _FakePaymentResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlipayPaymentPayload_5 extends _i1.SmartFake
    implements _i6.AlipayPaymentPayload {
  _FakeAlipayPaymentPayload_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClientAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientAdapter extends _i1.Mock implements _i2.HttpClientAdapter {
  @override
  _i7.Future<_i2.ResponseBody> fetch(
    _i8.RequestOptions? options,
    _i7.Stream<_i9.Uint8List>? requestStream,
    _i7.Future<void>? cancelFuture,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [options, requestStream, cancelFuture]),
            returnValue: _i7.Future<_i2.ResponseBody>.value(
              _FakeResponseBody_0(
                this,
                Invocation.method(#fetch, [
                  options,
                  requestStream,
                  cancelFuture,
                ]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.ResponseBody>.value(
              _FakeResponseBody_0(
                this,
                Invocation.method(#fetch, [
                  options,
                  requestStream,
                  cancelFuture,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.ResponseBody>);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TokenStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStore extends _i1.Mock implements _i10.TokenStore {
  @override
  _i7.Future<String?> readToken() =>
      (super.noSuchMethod(
            Invocation.method(#readToken, []),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String> readOrCreateClientId() =>
      (super.noSuchMethod(
            Invocation.method(#readOrCreateClientId, []),
            returnValue: _i7.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#readOrCreateClientId, []),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#readOrCreateClientId, []),
              ),
            ),
          )
          as _i7.Future<String>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i12.AuthService {
  @override
  _i7.Future<_i3.LoginResult> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i7.Future<_i3.LoginResult>.value(
              _FakeLoginResult_1(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.LoginResult>.value(
              _FakeLoginResult_1(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.LoginResult>);

  @override
  _i7.Future<void> register({
    required String? username,
    required String? password,
    String? nickname,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #username: username,
              #password: password,
              #nickname: nickname,
              #phone: phone,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.UserInfo> fetchCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentUser, []),
            returnValue: _i7.Future<_i3.UserInfo>.value(
              _FakeUserInfo_2(this, Invocation.method(#fetchCurrentUser, [])),
            ),
            returnValueForMissingStub: _i7.Future<_i3.UserInfo>.value(
              _FakeUserInfo_2(this, Invocation.method(#fetchCurrentUser, [])),
            ),
          )
          as _i7.Future<_i3.UserInfo>);
}

/// A class which mocks [HomeRecommendService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRecommendService extends _i1.Mock
    implements _i13.HomeRecommendService {
  @override
  _i7.Future<_i4.HomeRecommendPageResult> fetchRecommendProducts({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecommendProducts, [], {#page: page}),
            returnValue: _i7.Future<_i4.HomeRecommendPageResult>.value(
              _FakeHomeRecommendPageResult_3(
                this,
                Invocation.method(#fetchRecommendProducts, [], {#page: page}),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i4.HomeRecommendPageResult>.value(
                  _FakeHomeRecommendPageResult_3(
                    this,
                    Invocation.method(#fetchRecommendProducts, [], {
                      #page: page,
                    }),
                  ),
                ),
          )
          as _i7.Future<_i4.HomeRecommendPageResult>);
}

/// A class which mocks [PaymentGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentGateway extends _i1.Mock implements _i14.PaymentGateway {
  @override
  _i7.Future<_i5.PaymentResult> pay(_i15.PaymentRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#pay, [request]),
            returnValue: _i7.Future<_i5.PaymentResult>.value(
              _FakePaymentResult_4(this, Invocation.method(#pay, [request])),
            ),
            returnValueForMissingStub: _i7.Future<_i5.PaymentResult>.value(
              _FakePaymentResult_4(this, Invocation.method(#pay, [request])),
            ),
          )
          as _i7.Future<_i5.PaymentResult>);
}

/// A class which mocks [PaymentOrderProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentOrderProvider extends _i1.Mock
    implements _i16.PaymentOrderProvider {
  @override
  _i7.Future<_i6.AlipayPaymentPayload> fetchAlipayPayload(
    _i15.PaymentRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAlipayPayload, [request]),
            returnValue: _i7.Future<_i6.AlipayPaymentPayload>.value(
              _FakeAlipayPaymentPayload_5(
                this,
                Invocation.method(#fetchAlipayPayload, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i6.AlipayPaymentPayload>.value(
                  _FakeAlipayPaymentPayload_5(
                    this,
                    Invocation.method(#fetchAlipayPayload, [request]),
                  ),
                ),
          )
          as _i7.Future<_i6.AlipayPaymentPayload>);
}

/// A class which mocks [PaymentSdkInitializer].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentSdkInitializer extends _i1.Mock
    implements _i17.PaymentSdkInitializer {
  @override
  _i7.Future<void> initialize(_i18.AppConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [config]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
