// Mocks generated by Mockito 5.4.6 from annotations
// in my_first_app/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i8;
import 'dart:typed_data' as _i10;

import 'package:dio/src/adapter.dart' as _i2;
import 'package:dio/src/options.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:my_first_app/app/config/app_config.dart' as _i21;
import 'package:my_first_app/features/auth/data/auth_service.dart' as _i13;
import 'package:my_first_app/features/auth/data/models/user_info.dart' as _i3;
import 'package:my_first_app/features/auth/data/token_store.dart' as _i11;
import 'package:my_first_app/features/payment/application/payment_gateway.dart'
    as _i17;
import 'package:my_first_app/features/payment/application/payment_order_provider.dart'
    as _i19;
import 'package:my_first_app/features/payment/application/payment_sdk_initializer.dart'
    as _i20;
import 'package:my_first_app/features/payment/data/models/alipay_payment_payload.dart'
    as _i7;
import 'package:my_first_app/features/payment/data/models/payment_request.dart'
    as _i18;
import 'package:my_first_app/features/payment/presentation/models/payment_result.dart'
    as _i6;
import 'package:my_first_app/features/product/data/models/category_node.dart'
    as _i16;
import 'package:my_first_app/features/product/data/models/page_result.dart'
    as _i4;
import 'package:my_first_app/features/product/data/models/product_detail.dart'
    as _i5;
import 'package:my_first_app/features/product/data/models/product_summary.dart'
    as _i15;
import 'package:my_first_app/features/product/data/product_service.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponseBody_0 extends _i1.SmartFake implements _i2.ResponseBody {
  _FakeResponseBody_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResult_1 extends _i1.SmartFake implements _i3.LoginResult {
  _FakeLoginResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserInfo_2 extends _i1.SmartFake implements _i3.UserInfo {
  _FakeUserInfo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePageResult_3<T> extends _i1.SmartFake implements _i4.PageResult<T> {
  _FakePageResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductDetail_4 extends _i1.SmartFake implements _i5.ProductDetail {
  _FakeProductDetail_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentResult_5 extends _i1.SmartFake implements _i6.PaymentResult {
  _FakePaymentResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlipayPaymentPayload_6 extends _i1.SmartFake
    implements _i7.AlipayPaymentPayload {
  _FakeAlipayPaymentPayload_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClientAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientAdapter extends _i1.Mock implements _i2.HttpClientAdapter {
  @override
  _i8.Future<_i2.ResponseBody> fetch(
    _i9.RequestOptions? options,
    _i8.Stream<_i10.Uint8List>? requestStream,
    _i8.Future<void>? cancelFuture,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [options, requestStream, cancelFuture]),
            returnValue: _i8.Future<_i2.ResponseBody>.value(
              _FakeResponseBody_0(
                this,
                Invocation.method(#fetch, [
                  options,
                  requestStream,
                  cancelFuture,
                ]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.ResponseBody>.value(
              _FakeResponseBody_0(
                this,
                Invocation.method(#fetch, [
                  options,
                  requestStream,
                  cancelFuture,
                ]),
              ),
            ),
          )
          as _i8.Future<_i2.ResponseBody>);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TokenStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStore extends _i1.Mock implements _i11.TokenStore {
  @override
  _i8.Future<String?> readToken() =>
      (super.noSuchMethod(
            Invocation.method(#readToken, []),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> readOrCreateClientId() =>
      (super.noSuchMethod(
            Invocation.method(#readOrCreateClientId, []),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#readOrCreateClientId, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#readOrCreateClientId, []),
              ),
            ),
          )
          as _i8.Future<String>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i13.AuthService {
  @override
  _i8.Future<_i3.LoginResult> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i8.Future<_i3.LoginResult>.value(
              _FakeLoginResult_1(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.LoginResult>.value(
              _FakeLoginResult_1(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.LoginResult>);

  @override
  _i8.Future<void> register({
    required String? username,
    required String? password,
    String? nickname,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #username: username,
              #password: password,
              #nickname: nickname,
              #phone: phone,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.UserInfo> fetchCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentUser, []),
            returnValue: _i8.Future<_i3.UserInfo>.value(
              _FakeUserInfo_2(this, Invocation.method(#fetchCurrentUser, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i3.UserInfo>.value(
              _FakeUserInfo_2(this, Invocation.method(#fetchCurrentUser, [])),
            ),
          )
          as _i8.Future<_i3.UserInfo>);
}

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i14.ProductService {
  @override
  _i8.Future<_i4.PageResult<_i15.ProductSummary>> fetchProducts({
    int? categoryId,
    String? keyword,
    int? current = 1,
    int? size = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {
              #categoryId: categoryId,
              #keyword: keyword,
              #current: current,
              #size: size,
            }),
            returnValue: _i8.Future<_i4.PageResult<_i15.ProductSummary>>.value(
              _FakePageResult_3<_i15.ProductSummary>(
                this,
                Invocation.method(#fetchProducts, [], {
                  #categoryId: categoryId,
                  #keyword: keyword,
                  #current: current,
                  #size: size,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i4.PageResult<_i15.ProductSummary>>.value(
                  _FakePageResult_3<_i15.ProductSummary>(
                    this,
                    Invocation.method(#fetchProducts, [], {
                      #categoryId: categoryId,
                      #keyword: keyword,
                      #current: current,
                      #size: size,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i4.PageResult<_i15.ProductSummary>>);

  @override
  _i8.Future<_i5.ProductDetail> fetchProductDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductDetail, [id]),
            returnValue: _i8.Future<_i5.ProductDetail>.value(
              _FakeProductDetail_4(
                this,
                Invocation.method(#fetchProductDetail, [id]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.ProductDetail>.value(
              _FakeProductDetail_4(
                this,
                Invocation.method(#fetchProductDetail, [id]),
              ),
            ),
          )
          as _i8.Future<_i5.ProductDetail>);

  @override
  _i8.Future<List<_i16.CategoryNode>> fetchCategoryTree() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategoryTree, []),
            returnValue: _i8.Future<List<_i16.CategoryNode>>.value(
              <_i16.CategoryNode>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i16.CategoryNode>>.value(
                  <_i16.CategoryNode>[],
                ),
          )
          as _i8.Future<List<_i16.CategoryNode>>);
}

/// A class which mocks [PaymentGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentGateway extends _i1.Mock implements _i17.PaymentGateway {
  @override
  _i8.Future<_i6.PaymentResult> pay(_i18.PaymentRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#pay, [request]),
            returnValue: _i8.Future<_i6.PaymentResult>.value(
              _FakePaymentResult_5(this, Invocation.method(#pay, [request])),
            ),
            returnValueForMissingStub: _i8.Future<_i6.PaymentResult>.value(
              _FakePaymentResult_5(this, Invocation.method(#pay, [request])),
            ),
          )
          as _i8.Future<_i6.PaymentResult>);
}

/// A class which mocks [PaymentOrderProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentOrderProvider extends _i1.Mock
    implements _i19.PaymentOrderProvider {
  @override
  _i8.Future<_i7.AlipayPaymentPayload> fetchAlipayPayload(
    _i18.PaymentRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAlipayPayload, [request]),
            returnValue: _i8.Future<_i7.AlipayPaymentPayload>.value(
              _FakeAlipayPaymentPayload_6(
                this,
                Invocation.method(#fetchAlipayPayload, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i7.AlipayPaymentPayload>.value(
                  _FakeAlipayPaymentPayload_6(
                    this,
                    Invocation.method(#fetchAlipayPayload, [request]),
                  ),
                ),
          )
          as _i8.Future<_i7.AlipayPaymentPayload>);
}

/// A class which mocks [PaymentSdkInitializer].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentSdkInitializer extends _i1.Mock
    implements _i20.PaymentSdkInitializer {
  @override
  _i8.Future<void> initialize(_i21.AppConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [config]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
